name: display_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0-417.0.dev

# Add regular dependencies here.
dependencies:
  http: ^0.13.6
  image: ^4.0.17
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
